<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Biodata;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BiodataSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'nrp' => '31129999',
                'nama' => 'Budi Santoso',
                'nik' => '3201010101010001',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2000-01-01',
                'tinggi' => 170,
                'berat' => 65,
                'alamat' => 'Jl. Mawar No 1',
                'kecamatan' => 'Cicendo',
                'kelurahan' => 'Sukaraja',
                'kota' => 'Bandung',
                'kodepos' => '40111',
                'no_telp' => '0221234567',
                'handphone' => '081234567890',
                'hobby' => 'Membaca',
                'agama' => 'Islam',
                'warganegara' => 'Indonesia',
                'status_kawin' => 'Belum',
                'gol_darah' => 'O',
                'anak_ke' => 1,
                'jml_saudara' => 2,
                'jml_saudara_tanggungan' => 1,
                'sumber_biaya' => 'Orang Tua',
                'jenis_rmh' => 'Rumah',
                'asal_smu' => 'SMAN 1 Bandung',
                'lulus_smu' => '2018',
                'transportasi' => 'Motor',
                'nama_ayah' => 'Sutrisno',
                'alamat_ayah' => 'Bandung',
                'no_telp_ayah' => '0221111111',
                'kota_ayah' => 'Bandung',
                'kodepos_ayah' => '40111',
                'handphone_ayah' => '081111111111',
                'agama_ayah' => 'Islam',
                'pekerjaan_ayah' => 'Petani',
                'pendidikan_ayah' => 'SMA',
                'warganegara_ayah' => 'Indonesia',

                'nama_ibu' => 'Siti Aminah',
                'alamat_ibu' => 'Bandung',
                'kota_ibu' => 'Bandung',
                'kodepos_ibu' => '40111',
                'no_telp_ibu' => '0222222222',
                'handphone_ibu' => '082222222222',
                'agama_ibu' => 'Islam',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'pendidikan_ibu' => 'SMA',
                'warganegara_ibu' => 'Indonesia',

                'nama_wali' => 'Tidak Ada',
                'alamat_wali' => '-',
                'kota_wali' => '-',
                'kodepos_wali' => '00000',
                'no_telp_wali' => '-',
                'handphone_wali' => '-',
                'agama_wali' => '-',
                'pekerjaan_wali' => '-',
                'pendidikan_wali' => '-',
                'warganegara_wali' => '-',

                'special_need' => '1',
                'kps' => 0,
                'status_pendidikan' => 'A',
                'kebutuhan_ayah' => '0',
                'kebutuhan_ibu' => '0',
                'last_update' => Carbon::now(),
    
                'email' => 'budi@example.com',
                'jenis_kelamin' => 'L',
                'nisn' => '1234567890',
            ],

            [
                'nrp' => '31128888',
                'nama' => 'Andi Wijaya',
                'nik' => '3201010101010002',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2000-05-10',
              
                'tinggi' => 168,
                'berat' => 60,
                'alamat' => 'Jl. Melati',
                'kecamatan' => 'Antapani',
                'kelurahan' => 'Sukamaju',
                'kota' => 'Bandung',
                'kodepos' => '40112',
                'no_telp' => '0223333333',
                'handphone' => '081333333333',
                'hobby' => 'Olahraga',
                'agama' => 'Islam',
                'warganegara' => 'Indonesia',
                'status_kawin' => 'Belum',
                'gol_darah' => 'A',
                'anak_ke' => 2,
                'jml_saudara' => 3,
                'jml_saudara_tanggungan' => 1,
                'sumber_biaya' => 'Beasiswa',
                'jenis_rmh' => 'Kontrakan',
                'asal_smu' => 'SMAN 2 Bandung',
                'lulus_smu' => '2018',
                'transportasi' => 'Motor',
                

                'nama_ayah' => 'Bambang',
                'alamat_ayah' => 'Bandung',
                'no_telp_ayah' => '0224444444',
                'kota_ayah' => 'Bandung',
                'kodepos_ayah' => '40112',
                'handphone_ayah' => '081444444444',
                'agama_ayah' => 'Islam',
                'pekerjaan_ayah' => 'Wiraswasta',
                'pendidikan_ayah' => 'SMA',
                'warganegara_ayah' => 'Indonesia',

                'nama_ibu' => 'Susi',
                'alamat_ibu' => 'Bandung',
                'kota_ibu' => 'Bandung',
                'kodepos_ibu' => '40112',
                'no_telp_ibu' => '0225555555',
                'handphone_ibu' => '082555555555',
                'agama_ibu' => 'Islam',
                'pekerjaan_ibu' => 'Guru',
                'pendidikan_ibu' => 'S1',
                'warganegara_ibu' => 'Indonesia',

                'nama_wali' => 'Tidak Ada',
                'alamat_wali' => '-',
                'kota_wali' => '-',
                'kodepos_wali' => '00000',
                'no_telp_wali' => '-',
                'handphone_wali' => '-',
                'agama_wali' => '-',
                'pekerjaan_wali' => '-',
                'pendidikan_wali' => '-',
                'warganegara_wali' => '-',

                'special_need' => '0',
                'kps' => 0,
                'status_pendidikan' => 'A',
                'kebutuhan_ayah' => '0',
                'kebutuhan_ibu' => '0',
                'last_update' => Carbon::now(),

                'email' => 'andi@example.com',
                'jenis_kelamin' => 'L',
                'nisn' => '1234567891',
            ],

            [
                'nrp' => '31127777',
                'nama' => 'Siti Rahma',
                'nik' => '3201010101010003',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2000-08-20',
              
                'tinggi' => 160,
                'berat' => 50,
                'alamat' => 'Jl. Anggrek',
                'kecamatan' => 'Cimahi',
                'kelurahan' => 'Cibeureum',
                'kota' => 'Cimahi',
                'kodepos' => '40511',
                'no_telp' => '0226666666',
                'handphone' => '081666666666',
                'hobby' => 'Menulis',
                'agama' => 'Islam',
                'warganegara' => 'Indonesia',
                'status_kawin' => 'Belum',
                'gol_darah' => 'B',
                'anak_ke' => 1,
                'jml_saudara' => 1,
                'jml_saudara_tanggungan' => 1,
                'sumber_biaya' => 'Orang Tua',
                'jenis_rmh' => 'Rumah',
                'asal_smu' => 'SMAN 3 Cimahi',
                'lulus_smu' => '2018',
                'transportasi' => 'Jalan Kaki',
               

                'nama_ayah' => 'Rahmat',
                'alamat_ayah' => 'Cimahi',
                'no_telp_ayah' => '0227777777',
                'kota_ayah' => 'Cimahi',
                'kodepos_ayah' => '40511',
                'handphone_ayah' => '081777777777',
                'agama_ayah' => 'Islam',
                'pekerjaan_ayah' => 'Buruh',
                'pendidikan_ayah' => 'SMA',
                'warganegara_ayah' => 'Indonesia',

                'nama_ibu' => 'Nina',
                'alamat_ibu' => 'Cimahi',
                'kota_ibu' => 'Cimahi',
                'kodepos_ibu' => '40511',
                'no_telp_ibu' => '0228888888',
                'handphone_ibu' => '082888888888',
                'agama_ibu' => 'Islam',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'pendidikan_ibu' => 'SMA',
                'warganegara_ibu' => 'Indonesia',

                'nama_wali' => 'Tidak Ada',
                'alamat_wali' => '-',
                'kota_wali' => '-',
                'kodepos_wali' => '00000',
                'no_telp_wali' => '-',
                'handphone_wali' => '-',
                'agama_wali' => '-',
                'pekerjaan_wali' => '-',
                'pendidikan_wali' => '-',
                'warganegara_wali' => '-',

                'special_need' => '1',
                'kps' => 0,
                'status_pendidikan' => 'A',
                'kebutuhan_ayah' => '0',
                'kebutuhan_ibu' => '0',
                'last_update' => Carbon::now(),

                'email' => 'siti@example.com',
                'jenis_kelamin' => 'P',
                'nisn' => '1234567892',
            ],
        ];

        foreach ($data as $item) {
            Biodata::create($item);
        }
    }
}